Speicher_JSON Module BETA!!!!
snaptec/openWB pull request #1031
Opened 2021-02-09 17:32 UTC by DetMoerk

New Module to use Home Battery with JSON Output.
Can use complex jq Filters like PV_JSON and EVU_JSON
Description in moduleconfigbat.php has to be reworked.

2021-02-09 18:00 UTC, benderl requested changes

2021-02-09 18:00 UTC, benderl commented on modules/speicher_json/main.sh
> +	if (( $speicherleistung > 5 )); then
Warum erlaubst Du keine Werte größer 5? Ein Speicher kann geladen und entladen werden. Somit sind sowohl positive als auch negative Leistungen möglich.

2021-02-09 18:15 UTC, DetMoerk commented on modules/speicher_json/main.sh
> +	if (( $speicherleistung > 5 )); then
Upps, da hab ich nicht aufgepasst, als ich das aus dem PV_JSON übernommen habe.

2021-02-09 18:18 UTC, DetMoerk commented on modules/speicher_json/main.sh
> +	if (( $speicherleistung > 5 )); then
Wird jetzt 1:1 übernommen
Gut dass du drüber geschaut hast

2021-02-09 18:19 UTC, DetMoerk commented on modules/speicher_json/main.sh
> +	if (( $speicherleistung > 5 )); then
Wer es negiert benötigt kann hinter das Fileter *-1 machen

2021-02-09 18:32 UTC, benderl approved these changes

2021-02-09 18:33 UTC, merged

2021-02-10 12:48 UTC, DetMoerk commented
@benderl : hab gerade gesehen, dass da auch der falsche Name im Logfile drin ist. Kannst du das kurz fixen oder soll ich das heute Abend machen?

VG
Det

2021-02-10 13:28 UTC, benderl commented
Durch Zufall schon gesehen.