Viel bzw. wenig Überschuss beim Umschalten berechnen statt harter Werte
snaptec/openWB pull request #1075
Opened 2021-02-18 11:03 UTC by DanielRieker

Ich denke es macht Sinn an diesen Stellen den Wert aus  der Config für die Einschaltschwelle (mindestuberschuss) mit den 3 Phasen zu multiplizieren, statt hart von 5000 bw. 7000 Watt für die Aktivierung bzw. Deaktivierung der 3 phasigen Ladung auszugehen. 

Ich hatte jetzt schon den Fall, dass die Umschaltung von 1 auf 3 Phasen nicht funktioniert hat, weil direkt nach der abgeschlossenen Umschaltung noch keine Ladung aktiv war und weniger al 5000 Watt Überschuss vorhanden waren. Dann wurde noch vor der wiederaufnahme der Ladung mit 3 Phasen auf 1 Phase zurückgeschalten.

Kann natürlich auch sein, dass ich hier einen kompletten Denkfehler hab ;-)

2021-02-18 17:28 UTC, benderl commented
Die Grenzen zum Umschalten dürfen nicht identisch sein, sondern müssen eine Hysterese haben. Ansonsten kommt es zu einem ungewollt, hektischen Verhalten.

2021-02-18 19:58 UTC, DanielRieker commented
OK, das klingt logisch... Wäre es dann ein guter Weg, auf die aktuelle Berechnung immer noch z.B. 250 oder 500 Watt Hysterese drauf zu rechnen?

2021-02-22 19:15 UTC, snaptec commented
250 Watt ist bei einem flukuativen Hausverbrauch leider etwas arg wenig. 1-2 kW sollten es durchaus sein das beim dreiphasigen Start etwas Luft ist.
Entsprechend auch 1 kW Luft für das zurück schalten.
daher auch die 5kW / 7kW als Grenze. Diese könnten von mir aus auch dynamisch sein. Aber wenigstens 1-2 kW Hysterie sollte drinnen sein.

2021-02-23 06:03 UTC, DanielRieker commented
Ich hab den Wert, der als Hysterie draufgerechnet wird, auf 1kW geändert...

2021-02-25 14:04 UTC, benderl commented
Nach der kommenden Stable wird der PR übernommen.
Danke für Deinen Beitrag zu openWB!

2021-03-15 14:22 UTC, DanielRieker commented
@benderl Da die Stable nun ein paar Tage alt ist wollt ich kurz nachfragen ob du den PR noch übernimmst ;-)

2021-03-15 14:29 UTC, benderl commented
Es kommt noch ein schneller Bugfix Release für die Stable und dann kommt er rein.

2021-03-15 19:02 UTC, DanielRieker commented
Top 👍

2021-03-18 10:07 UTC, benderl requested changes
Anscheinend ist die Hysterese zwischendurch verloren gegangen.
Bitte die Anmerkungen beachten.

2021-03-18 10:07 UTC, benderl commented on u1p3p.sh
> +									if (( uberschuss < ((3 * mindestuberschuss) + 1000) )); then
Bitte das Offset +100W hier entfernen, da wir ansonsten wieder identische Grenzen zum Umschalten haben.

2021-03-18 10:07 UTC, benderl commented on u1p3p.sh
> +									if (( uberschuss < ((3 * mindestuberschuss) + 1000) )); then
Bitte das Offset +100W hier entfernen, da wir ansonsten wieder identische Grenzen zum Umschalten haben.

2021-03-18 10:39 UTC, DanielRieker commented
Verstehe ich jetzt nicht, der Initiale commit war ohne den Offset, dann hab ich den erst mit 250 Wattt und nun auf 1000 Watt geändert. Das ist nach meinem Verständnis die Hysterese. Soll ich das wieder auf den Stand hier zurück ändern: https://github.com/snaptec/openWB/pull/1075/commits/7624a1e257a322f8f5cddd7ed6b925f337161627

2021-03-18 10:42 UTC, benderl commented
In der ursprünglichen Version wird auf >7000W und <5000W geprüft. Das sind 2000W Unterschied.
Bei Dir wird immer auf den selben Wert getestet, also ist keine Hysterese vorhanden. Wenn Du an den beiden angemerkten Stellen die +1000 entfernst, haben wir die gewollte Differenz von 1000W.

2021-03-18 10:50 UTC, benderl commented
Danke!

2021-03-18 10:50 UTC, DanielRieker commented
Jetzt hab ich erst verstanden, die Hysterese hatte ich bisher nie wirklich eingabaut weil ich immer bei Start 3 Phasen und Stop 3 Phasen denselben Offset drauf gerechnet hab... 🙃 Hab ich nun korrigiert.

2021-03-18 10:50 UTC, merged