SoC HTTP Intervallvorgabe (beta)
snaptec/openWB pull request #1198
Opened 2021-03-18 09:18 UTC by Bucky2k

Anbei eine Intervallvorgabe für das HTTP Modul wie unter Issue angefragt. Nicht getestet mangels http SoC Quelle!

#1178

2021-03-18 10:31 UTC, benderl requested changes
Bitte die Logik der main.sh nochmal prüfen. Das kann so nicht funktionieren.

2021-03-18 10:31 UTC, benderl commented on modules/soc_http/main.sh
>  soc=$(curl --connect-timeout 15 -s $ip | cut -f1 -d".")
Die Zeile müsste dann doch wegfallen. Ansonsten wird nach wie vor immer die URL aufgerufen.

2021-03-18 10:31 UTC, benderl commented on modules/soc_http/main.sh
> +		if [ $soc -eq 0 ]; then
Die Abfrage würde nur den SoC 0% als gültig ansehen. In der ursprünglichen Implementierung wurde der Exitcode `$?` eines Funktionsaufrufes ausgewertet. Hier jedoch wird der SoC direkt ausgegeben. Daher sollte die ursprüngliche Prüfung mit dem regulären Ausdruck verwendet werden.

2021-03-18 10:52 UTC, Bucky2k commented on modules/soc_http/main.sh
>  soc=$(curl --connect-timeout 15 -s $ip | cut -f1 -d".")
Korrekt, diese habe ich leider versäumt zu löschen

2021-03-18 11:10 UTC, benderl commented on modules/soc_http/main.sh
> +		echo 0 > $soctimerfile
Die Zeile ist doppelt drin (43).

2021-04-06 22:43 UTC, Bucky2k commented
Leider meinen Fork gelöscht, daher V2: #1271

2021-04-06 22:43 UTC, closed without merging