EVU Module Powerfox
snaptec/openWB pull request #1206
Opened 2021-03-19 15:45 UTC by mutsch75

Integration von Powerfox als EVU Modul
Doku zur API:
https://www.powerfox.energy/wp-content/uploads/2020/05/powerfox-Kunden-API.pdf

2021-03-19 15:47 UTC, mutsch75 commented
Ich hoffe mal ich hab nichts vergessen

2021-03-20 08:14 UTC, benderl requested changes
Danke für den PR. Bitte noch die beiden anderen Parameter in der updateConfig.sh ergänzen.

2021-03-20 08:14 UTC, benderl commented on runs/updateConfig.sh
> +		echo "powerfoxid=idesmeters" >> $ConfigFile
Hier sollten auch user und pass ergänzt werden.

2021-03-20 09:08 UTC, mutsch75 commented on runs/updateConfig.sh
> +		echo "powerfoxid=idesmeters" >> $ConfigFile
ergänzt

2021-03-20 22:10 UTC, benderl approved these changes

2021-03-20 22:11 UTC, merged