added Module for Studer WR
snaptec/openWB pull request #1340
Opened 2021-04-25 14:54 UTC by eisenkoch

allows Monitoring Studer XTender (XTS/XTH/XTM) and MPPT Charger (VS + VT)

2021-04-28 18:01 UTC, eisenkoch commented
es wäre schön wenn wir das noch in die nächste Beta mit reinkommen könnten. Dann ist das Modul erst einmal vollständig

2021-05-03 04:59 UTC, snaptec requested changes

2021-05-03 05:44 UTC, eisenkoch commented on modules/wr_studer/main.sh
> +sudo python /var/www/html/openWB/modules/wr_studer/studer_wr.py $studer_ip $studer_xt $studer_vc $studer_vc_type
sudo is now removed. (i coppied this from other modules)

2021-05-03 14:40 UTC, eisenkoch reviewed
solved

2021-05-05 10:17 UTC, merged