Alternative EVU+Batterie-Module für Solarwatt/MyReserve-Geräte mit Gateway
snaptec/openWB pull request #1362
Opened 2021-05-05 08:47 UTC by Flock82

Ersatz für #1348

2021-05-05 09:22 UTC, benderl requested changes
Sind zwingend zwei IP-Adressen notwendig oder kann der WR auch über das Gateway abgefragt werden?

2021-05-05 09:22 UTC, benderl commented on runs/updateConfig.sh
> +		echo "speicher1_ip2=192.168.0.17" >> $ConfigFile
Dieser Eintrag wird nie ergänzt werden, da in einer vorherigen Version bereits `bezug1_ip` vorhanden war. Bitte in einem eigenen IF ergänzen, falls das wirklich notwendig ist (siehe anderer Kommentar).

2021-05-05 09:22 UTC, benderl commented on web/settings/modulconfigbat.php
> +						<div id="divspeicherip2" class="hide">
Den Block bitte nur einblenden, wenn `solarwattmethod = 1` gilt.

2021-05-05 09:22 UTC, benderl commented on web/settings/modulconfigbat.php
> +								<div class="alert alert-info">
Bitte die Einrückung korrigieren.

2021-05-05 13:20 UTC, Flock82 commented
Änderungen sind drinnen.
Das Gateway liefert leider nur die PV-Daten für den PV-Strang, in dem die Batterie hängt, daher müssen die WR-Daten an anderer Stelle abgegriffen werden. Am liebsten wäre mir der WR selber, da der Energy Manager von Solarwatt ziemlicher Murks ist, aber dann wäre die Batterie-Leistung doppelt berücksichtigt, da diese ja vor dem WR hängt.

2021-05-12 06:28 UTC, benderl approved these changes

2021-05-12 06:29 UTC, merged