SoC-Text-update
snaptec/openWB pull request #1676
Opened 2021-11-03 16:20 UTC by MartinRinas

Beschreibungstexte für SoC Limit angepasst (Ladestopp bei Überschreitung, nicht bei Erreichen)

2021-11-05 18:51 UTC, benderl requested changes
Danke für die Anpassung. Bitte noch den einen Text korrigieren.

2021-11-05 18:51 UTC, benderl commented on web/settings/pvconfig.html
> +									<span class="form-text small">Parameter in Prozent [%] für den Maximal-SoC am LP1 im Modus PV-Laden. Definiert einen EV-Maximal-SoC, Definiert einen EV-Maximal-SoC, bei dessen Überschreitung
Hier sind ein paar Worte doppelt.

2021-11-06 11:05 UTC, MartinRinas commented on web/settings/pvconfig.html
> +									<span class="form-text small">Parameter in Prozent [%] für den Maximal-SoC am LP1 im Modus PV-Laden. Definiert einen EV-Maximal-SoC, Definiert einen EV-Maximal-SoC, bei dessen Überschreitung
oh ja, da hab' ich mich wohl zu ambitioniert beim copy&paste.

2021-11-06 11:18 UTC, benderl approved these changes

2021-11-06 11:19 UTC, merged