E3DC Bezug Anpassung V2 Korrektur
snaptec/openWB pull request #1941
Opened 2022-01-18 16:05 UTC by okaegi

Simcount wird nun direkt im Bezugsmodul e3dc gelesen
Simcount für e3dc Bezug im Loadvars.sh entfernt
Simcount (SimCountFactory) für V2 persistiert nun korrekt die EVU Topics (Lösung mit @yankee42 erarbeitet), Zähler fing nach Reboot bei 0 an da er nur auf ganze Zahlen (nicht float) checkte
Dadurch sollte das Daily Excel wieder stimmen

2022-01-18 16:49 UTC, yankee42 commented on modules/bezug_e3dc/e3dc.py
> +        exported= float("%.3f" % cnt[1]),
einfach nur `imported=cnt[0]` genügt völlig. Das Gleiche für `exported`

2022-01-18 16:49 UTC, yankee42 commented on packages/modules/common/simcount.py
> +                float(self.temp)
Das ganze wird dann trotzdem unten als String zurückgegeben und dann doch wieder ein float draus.

Besser:
```python
try:
    result = float(self.temp)
except ValueError:
    result = 0
return result
```
Dann kommt immer eine Zahl zurück.

2022-01-18 17:47 UTC, okaegi commented
Yanniks hinweise umgesetzt

2022-01-18 17:47 UTC, okaegi commented on packages/modules/common/simcount.py
> +                float(self.temp)
geändert

2022-01-18 17:47 UTC, okaegi commented on modules/bezug_e3dc/e3dc.py
> +        exported= float("%.3f" % cnt[1]),
geändert

2022-01-19 08:08 UTC, benderl requested changes

2022-01-19 08:08 UTC, benderl commented on packages/modules/common/simcount.py
> +                    counter_import_present = int(float(Restore().restore_value("watt0pos", prefix)))
Da `Restore().restore_value()` jetzt immer ein Float zurückgibt, kann die Konvertierung hier entfallen.

2022-01-19 08:57 UTC, okaegi commented on packages/modules/common/simcount.py
> +                    counter_import_present = int(float(Restore().restore_value("watt0pos", prefix)))
Gemacht

2022-01-19 09:32 UTC, benderl approved these changes

2022-01-19 09:32 UTC, merged