Systeminfo erweitert
snaptec/openWB pull request #1943
Opened 2022-01-18 17:42 UTC by hhoefling

Es werden der Platz auf der SD als auch der Platz in der Ramdisk Platz dargestellt
Es werden die beiden, inzwischen ja einstellbaren, virutellen IP-Adressen angezeigt.

2022-01-19 08:03 UTC, benderl requested changes
Kannst Du bitte noch die Einrückung in `web/tools/programmloggerinfo.php` korrigieren?
Space -> Tab

2022-01-20 09:34 UTC, benderl approved these changes

2022-01-20 20:48 UTC, benderl commented
Ich denke, der letzte Commit gehört hier nicht rein.

2022-01-20 23:25 UTC, hhoefling commented
Ja, stimmt. 
Wenn du kannst trenn ihn ab / lass ihn weg
Erklar mir wie man das verhindern kann.....

2022-01-21 08:15 UTC, benderl commented
So einfach kann ich das nicht über GitHub. Ein PR kann nur vollständig gemerged werden.
Nutze doch bitte für PRs eigene Branches und nicht Deinen master.

2022-01-21 08:15 UTC, closed without merging

2022-01-21 08:47 UTC, yankee42 commented
> Ja, stimmt. Wenn du kannst trenn ihn ab / lass ihn weg Erklar mir wie man das verhindern kann.....

Um sowas in Zukunft zu verhindern mache keine Pull-Requests auf master, sondern verwende für jedes Feature einen separaten branch.

Um diesen PR hier aufzuräumen kannst du wie folgt vorgehen:

1. Falls noch nicht der Fall ist, das offizielle Repository zu git hinzufügen. Als Name nehme ich `upstream`:
    ```bash
    # Entweder per SSH, wenn du SSH mit keyfile verwendest:
    git remote add upstream git@github.com:snaptec/openWB.git
    # Oder HTTPS, wenn nicht:
    git remote add upstream https://github.com/snaptec/openWB.git
    ```
2. Sicherstellen, dass `upstream` aktuell ist:
    ```bash
    git fetch upstream
    ```
3. Deinen branch auf den aktuellen upstream-master rebasen:
    ```bash
    git rebase -i upstream/master 
    ```
    Es öffnet sich ein Editor in dem folgendes steht:
    ```
    pick 04810e94 80=80 Teil 1, Nachtladen
    pick 20a3341b Lösung für 80=80.  (Trotzdem dauerladen bei Ziel=100)
    pick 5e66d331 80=80 Teil 1, Nachtladen
    pick 247bef13 Lösung für 80=80.  (Trotzdem dauerladen bei Ziel=100)
    pick 15f87e97 Systeminfo erweitert
    pick 637d42d5 Systeminfo, nachzüegler..... :-(
    pick 9c47abbb Logfile cleaning optimiert.
    pick 963bb29f Spac->Tab
    ```
    Einfach jetzt alle Zeilen entfernen, die mit diesem PR nichts zu tun haben, speichern, fertig. Optional noch commits zusammenfassen, die eine logische Einheit bilden: Git fängt bei dem Rebase mit dem Original master-branch an und nimmt dann die commits aus dem angezeigten Text von oben nach unten und wendet sie neu an. Dabei kann es auch commits zusammenfassen, editieren, commit-Nachrichten ändern etc. Mein Vorschlag wäre die Datei so aussehen zu lassen:
    ```
    pick 15f87e97 Systeminfo erweitert
    fixup 637d42d5 Systeminfo, nachzüegler..... :-(
    fixup 963bb29f Spac->Tab
    ```
    Heißt der erste commit wird genommen, die anderen beiden werden in den ersten commit integriert und die commit-Nachricht verworfen. Am Ende bleibt ein branch mit einem commit mit all deinen Änderungen übrig. Der commit "Logfile cleaning optimiert." scheint mir nicht zu diesem PR hier zu passen. Wenn der doch drin bleiben soll, dann kann es auch so aussehen:
    ```
    pick 15f87e97 Systeminfo erweitert
    fixup 637d42d5 Systeminfo, nachzüegler..... :-(
    fixup 963bb29f Spac->Tab
    pick 9c47abbb Logfile cleaning optimiert.
    
    ```
    Dann bleiben am Ende zwei commits übrig. Da das "logfile cleaning optimiert" eine separate Einheit bildet ist es sinnvoll das als eigenen commit stehen zu lassen.
4. Das ganze auf deinen Fork force-pushen:
    ```bash
    git push -f origin master
    ```
    Dann den branch `master` nicht mehr anfassen bis der PR gemergt ist.

2022-01-21 14:53 UTC, hhoefling commented
> 4\. Dann den branch `master` nicht mehr anfassen bis der PR gemergt ist.

Was bei mir bedeuten würd eine Woche lang nichts mehr tun