new SoC module for Aiways
snaptec/openWB pull request #1993
Opened 2022-02-03 20:24 UTC by 0815eddi

new SoC module for Aiways
Includes the subdirectories soc_aiways (main.sh, aiways_get_soc.py) and soc_aiways_lp2 (main.sh).
Also changes in modulconfiglp.php are made to give the possibility to select and configure the Aiways Module.
The relevant parameters have been added to openwb.conf

2022-02-04 09:57 UTC, benderl requested changes
Danke für Deinen PR. Bitte noch meine Anmerkungen beachten.

2022-02-04 09:57 UTC, benderl commented on modules/soc_aiwayslp2/main.sh
> +# functionality is in soc_carnet
Den Kommentar bitte an Dein Modul anpassen.

2022-02-04 09:57 UTC, benderl commented on web/settings/modulconfiglp.php
> +							if($('#socmodul1').val() == 'soc_audilp2') {
Der Codeblock gehört nicht zu Deinem Modul. Bitte die Änderungen entfernen.

2022-02-04 09:57 UTC, benderl commented on openwb.conf
> +aiwayslp2intervall=''
Hier fehlt noch ein Zeilenumbruch am Ende der Datei.

2022-02-04 09:57 UTC, benderl commented on openwb.conf
> +aiwaysuser=''
Damit bestehende Installationen beim Update die Einstellungen erhalten können, müssen diese in der `runs/updateConfig.sh` ergänzt werden.

2022-02-05 21:41 UTC, 0815eddi commented
Danke für die Anmerkungen. 
Wurde soweit alles umgesetzt. Zusätzlich habe ich die Parameter noch mal umbenannt (mit einem beginnenden "soc_" ).
Die Änderungen habe ich soeben commited - muss ich sonst noch was machen?

2022-02-08 11:54 UTC, benderl approved these changes
Sieht gut aus.

2022-02-08 11:55 UTC, merged