solax gen4
snaptec/openWB pull request #2150
Opened 2022-04-14 05:35 UTC by okaegi

Solax gen4
Bestehnden Solax gen3 Treiber angepasst. Als zusätzliches Eingabefeld wird neu Modbus ID verlangt. Gen4 verlangt hier ein Wert, gen3 sollte mit 0 laufen

2022-04-25 09:52 UTC, benderl requested changes
Siehe inline Kommentar.

2022-04-25 09:52 UTC, benderl commented on web/settings/modulconfigpv.php
> +									<input class="form-control" type="text" name="pv1_ida" id="pv1_ida" value="<?php echo $pv1_idaold ?>">
Es gibt bereits ein Input Element mit dieser ID.
Das entsprechende DIV mit der ID "pvid" muss nur per JS eingeblendet werden (Z. 1014).

2022-04-25 14:22 UTC, okaegi commented on web/settings/modulconfigpv.php
> +									<input class="form-control" type="text" name="pv1_ida" id="pv1_ida" value="<?php echo $pv1_idaold ?>">
ist angepasst

2022-04-25 14:28 UTC, okaegi commented
PVID wiederverwendet

2022-04-28 18:17 UTC, benderl approved these changes

2022-04-28 18:18 UTC, merged