minor bug fixes; python-style equals NoneType
snaptec/openWB pull request #2266
Opened 2022-06-28 16:24 UTC by itnaegele

Speicher_json hat bei mir nicht funktioniert, nach einigen Edits tut es nun für mich - bitte prüfen, bin kein Python-Entwickler, wollte nur etwas ans Projekt zurückgeben. hth

2022-06-29 08:10 UTC, LKuemmel requested changes

2022-06-29 08:10 UTC, LKuemmel commented on packages/modules/json/bat.py
> +            power = 0
```suggestion
        power = jq.compile(config["jq_power"]).input(response).first()
```
Die Leistung des Speichers muss ausgelesen werden, da dieser sonst nicht in der Regelung berücksichtigt werden kann. `None` ist der default-Value, der vom Benutzer überschrieben werden muss.

2022-06-29 08:25 UTC, itnaegele commented
danke für das schnelle Review - das wusste ich nicht. Hab die Änderungen akzeptiert und teste es.

2022-06-29 08:26 UTC, LKuemmel approved these changes

2022-07-01 08:03 UTC, LKuemmel commented
@itnaegele Funktioniert es bei Dir?

2022-07-04 08:17 UTC, merged