logging/validierung von mqtt  parameter
snaptec/openWB pull request #2267
Opened 2022-06-29 05:09 UTC by okaegi

Neu werden beim ReRead und dem Start alle gelesenen mqtt Parameter protokolliert und validiert. Dazu wird die Datei smartcon.log erstellt, welches nur die Config parameter enthält. Der Startup wurde leicht geändert, um dem null (alle config Parameter weg) Problem auf die Spur zu kommen. Aus jetziger Sicht läuft zu viel parallel auf dem mqtt Broker so dass nicht innert 5 Sekunden alle smarthome parameter gelesen werden können.

2022-06-29 08:34 UTC, LKuemmel commented on runs/smarthomemq.py
> +
Warum verwendest Du hier nicht das Logging-Modul von Python?

2022-06-29 08:58 UTC, okaegi commented
Es geht hier drum eine Fehlersituation zu finden. Die Parameter werden heute schon alle im smarthome.log protokolliert.https://openwb.de/forum/viewtopic.php?p=67356#p67356Diese neue log beinhalter nur die gleichen  mqtt topics die vom Smarthomemq gelesen werden. Das Smarthomelog wird allerdings nach 2000 Records truncated, somit nutzt das bestehende smarthome log nichts wenn ich Aussagen habe: openwb vergisst immer mal wieder alle mqtt topics. Somit werden in dem neuen log nur die mqtt parameter mitgeschrieben. Dieses neue log wird auch nach 2000 Records truncated, sollte aber die mqtt Parameter von eine Woche protokollieren können da sonst nichts in den log steht.Gruss OluverAm 29.06.2022 10:34 schrieb LKuemmel ***@***.***>:
@LKuemmel commented on this pull request.



In runs/smarthomemq.py:
> +def logCon(level, msg):
+    if (int(level) >= LOGLEVELDEBUG):
+        local_time = datetime.now(timezone.utc).astimezone()
+        with open(bp+'/ramdisk/smartcon.log', 'a', encoding='utf8',
+                  buffering=1) as f:
+            if (int(level) == 0):
+                f.write(local_time.strftime(format="%Y-%m-%d %H:%M:%S")
+                        + '-: ' + str(msg) + '\n')
+            if (int(level) == 1):
+                f.write(local_time.strftime(format="%Y-%m-%d %H:%M:%S")
+                        + '-: ' + str(msg) + '\n')
+            if (int(level) == 2):
+                f.write(local_time.strftime(format="%Y-%m-%d %H:%M:%S")
+                        + '-: ' + str(msg) + '\n')
+
+

Warum verwendest Du hier nicht das Logging-Modul von Python?

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-06-30 13:07 UTC, LKuemmel requested changes

2022-06-30 13:07 UTC, LKuemmel commented on runs/usmarthome/smartbase0.py
> +        self.log = logging.getLogger("smarthome")
Wenn ein Logger mit dem Namen `smarthome` erstellt wurde, reicht es, ein `log = logging.getLogger("smarthome")` an den Anfang des Moduls zu stellen und der Logger kann im Modul verwendet werden. Er muss dann kein Klassenattribut sein.

2022-07-01 07:58 UTC, LKuemmel requested changes

2022-07-01 07:58 UTC, LKuemmel commented on runs/smarthomemq.py
> +    global log
Werden die globalen Variablen hier jetzt noch benötigt?

2022-07-01 08:16 UTC, okaegi commented
Hallo Lena,Wenn wir die Varable ausserhab einer Funktion definieren und die Variable nur lesend verwendet braucht es die global Definition nicht. Sofern du die Variable schreiben willst, brauchst du dann nach meinem Kentnissstand das global keyword. Somit verwende ich wenig globale Variablen. Und wenn da verwende ich das global keyword in den Funktionen. Wenn gewünscht kann ich es ändern, sag Bescheid.Also, use the global keyword if you want to change a global variable inside a function.Gruss OliverAm 01.07.2022 09:58 schrieb LKuemmel ***@***.***>:

@LKuemmel requested changes on this pull request.







In runs/smarthomemq.py:

> +    global log_config

+    global log



Werden die globalen Variablen hier jetzt noch benötigt?



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-07-01 14:17 UTC, merged