fix: `request_value` is never called with "none", result is always float
snaptec/openWB pull request #2337
Opened 2022-07-29 11:57 UTC by yankee42

Zufällig ist mir im HTTP-Modul merkwürdiges aufgefallen:
- Die Funktion `request_value` sagt:
    ```python
    if "none" == url:
        return None
    ```
    Aber diese Funktion wird niemals mit "none" aufgerufen. Der einzige Ort von dem aus die Funktion aufgerufen wird ist aus `create_request_function`. Diese überprüft den Pfad bereits vor dem Aufruf. Denkbar wäre lediglich dass jemand zum Beispiel `create_request_function("No", "ne")` aufruft. Aber der Fall erscheint mir eher abwegig. Insofern ist dieser Test unnötig und das Ergebnis ist immer garantiert ein `float` und niemals `None`.
    
    Das `if` ist seit #1832 unnötig. Da habe ich wohl übersehen das `if` zu entfernen.
    
    In #2200 bzw. genau genommen in commit af6b1dc779e8eafaf5dfdd7e0b5e5bb77560aa44 kam die Änderung rein, dass die Funktion `None` statt `0` zurückgibt. Leider sagt weder die Beschreibung des PR noch die commit message etwas darüber aus, was eigentlich das Problem war. Eventuell sollte zwischen "unbekannten Wert" und "0" unterschieden werden, was durchaus Sinn ergeben würde. Das wird so allerdings nicht erreicht.
- Seit 9a977210676cc68a668ec54d52aa03ba1e0b4c75 akzeptiert die Funktion `create_request_function` auch `None` als `path`. Das ist in der Type-Annotation nicht korrekt wiedergegeben.
- Der Aufruf
    ```python
    response.encoding = 'utf-8'
    ```
    Ist nicht sinnvoll. Das Encoding wird vom Server per HTTP-Header auf den tatsächlichen Wert gesetzt. Hiermit wird das encoding überschrieben. In den allermeisten Fällen wird UTF-8 wohl gut gehen und der requests-Decoder ist auch so eingestellt, dass er Fehler "verzeiht", so dass es dadurch zwar selten zum Schaden kommen dürfte, aber sinnvoll ist das deswegen trotzdem nicht. Ich habe die Zeile gestrichen.
- Der Logaufruf
    ```python
    log.debug("Antwort auf "+str(url)+" "+str(response.text))
    ```
    ist unnötig kompliziert. Der Logging-Framework unterstützt direkt Formatierung. Das hat auch den Vorteil, dass der Log-String nicht gebaut werden muss, wenn es wegen den Loglevel nicht zur Logausgabe kommt. (Wobei man auch überlegen könnte das logging ganz sein zu lassen, denn zumindest der Response body (nicht jedoch die request-URL) wird bereits in einem hook von der http-session geloggt).
- In af6b1dc779e8eafaf5dfdd7e0b5e5bb77560aa44 wurde aus `def create_request_function(domain: str, path: str) -> Callable[[], Union[int, float]]` -> `def create_request_function(domain: str, path: str) -> Callable[[], Optional[float]]:`. Ist aber nicht richtig, denn es kann so wie es jetzt ist nicht `None` sein, aber es kann auch ein `int` sein, also wie vorher beschrieben. Ich habe es jetzt auf "nur float" geändert.

2022-07-29 13:24 UTC, yankee42 commented
Ich habe doch etwas gefunden worum es wohl dabei ging, dass das Ergebnis `None` ist:
https://github.com/snaptec/openWB/blob/a7dc53d7665257dfac1baeaf881d07c894021b8e/packages/modules/http/bat.py#L32-L37

Das dürfte meiner Einschätzung nach aus den oben beschriebenen Gründen nicht funktionieren. Oder übersehe ich etwas? Hat das schonmal jemand erfolgreich getestet?

Ganz so einfach da dann `None` reinzuschreiben ist es jedoch nicht, denn an anderer Stelle wird eben 0 erwartet wenn nichts konfiguriert ist. Es müssten dann alle anderen Stellen angepasst werden. Das ist kein Problem und wäre finde ich auch durchaus logisch zu tun...

2022-08-17 12:33 UTC, LKuemmel requested changes

2022-08-17 12:33 UTC, LKuemmel commented on packages/modules/http/api.py
> +        return lambda: 0.0
```suggestion
        return lambda: None
```
Hier muss dann `None` zurückgegeben werden, wenn nichts konfiguriert ist.

2022-08-17 12:33 UTC, LKuemmel commented on packages/modules/http/api.py
> +    log.debug("Antwort auf %s: %s", url, response_text)
Stimmt, diese Zeile wird durch den Hook obsolet.
Im Hook [https://github.com/snaptec/openWB/blob/49e6913ea2d2cb9be5e113304b9f2e30abde0add/packages/modules/common/req.py#L11](https://github.com/snaptec/openWB/blob/49e6913ea2d2cb9be5e113304b9f2e30abde0add/packages/modules/common/req.py#L11) könnte man noch die Meldung anpassen:
`session.hooks['response'].append(lambda r, *args, **kwargs: log.debug("Get-Response von " + r.url + ": " + r.text))`

2022-09-15 15:10 UTC, merged