Enphase inverter and counter (no battery yet)
snaptec/openWB pull request #2393
Opened 2022-09-05 13:04 UTC by Stefan-Olt

This adds support for the Enphase PV and EVU counter. It uses the recommended JSON-API calls that still exists in firmware version 7.x
Firmware version 7.x is not supported yet, as it requires special authorization which I cannot test (you'll get an upgrade to version 7 when you install a storage "Encharge"). Therefore this module will not work yet with a storage installed.
The EID values can be read from /ivp/meters. Support for automatic detection could be added in future.

2022-09-13 07:13 UTC, LKuemmel requested changes

2022-09-13 07:13 UTC, LKuemmel commented on web/settings/modulconfigpv.php
> +								<label for="wrenphasehostname" class="col-md-4 col-form-label">Envoy / IQ-Gateway IP/Hostname</label>
Hier bitte noch eine Info-Box, wie zB beim Janitza-Zähler, hinzufügen, dass nur die Firmware älter als Version 7 unterstützt wird.

2022-09-13 07:13 UTC, LKuemmel commented on packages/modules/enphase/config.py
> +        self.name = name
Kannst Du die Config-Datei bitte noch an die Änderungen anpassen, die mit PR #2339 reingekommen sind?

2022-10-03 20:28 UTC, Stefan-Olt commented on web/settings/modulconfigpv.php
> +								<label for="wrenphasehostname" class="col-md-4 col-form-label">Envoy / IQ-Gateway IP/Hostname</label>
Habe ich ergänzt

2022-10-03 20:29 UTC, Stefan-Olt commented
Habe die Änderungen eingepflegt, hoffe da ist in der Zwischenzeit nichts dazu gekommen

2022-10-04 10:09 UTC, LKuemmel commented
Sorry, mein Änderungsvorschlag war falsch. Die Zeilen waren richtig. Nur die Konfiguration der Komponenten erbt die ComponentSetup-Klasse. Kannst Du das bitte nochmal anpassen?

2022-10-04 10:09 UTC, LKuemmel commented
Flake8 hat noch ein paar Formatierungs-Fehler festgestellt. Nutzt Du einen Python-Formatter?

2022-10-04 15:30 UTC, Stefan-Olt commented
Hatte beim kopieren von der openWB auf meinen Arbeitsrechner ein Fehler eingebaut, jetzt sieht mit flake8 alles sauber aus

2022-10-06 09:28 UTC, LKuemmel approved these changes

2022-10-06 09:28 UTC, merged