add support for Siemens SENTRON (7KM PAC2200) measuring devices
snaptec/openWB pull request #2402
Opened 2022-09-09 22:20 UTC by nalxnet

Currently, Siemens SENTRON (7KM PAC2200) energy meters can be used in the EVU module of openWB by choosing the generic JSON module and parsing the power/import/export values from the energy meter's webpage data URLs. However, this is limited to measuring only the basic EVU values and also has the unnecessary performance overhead of HTTP and JSON parsing.

This commit introduces a custom implementation for these energy meters. It reads all EVU values openWB can process directly from the energy meter via Modbus/TCP. Users only have to enter the meter's IP address.

This implementation has been tested in my home installation. All values correspond to the ones displayed in the meter's webpage and no performance issues for running the control loop could be detected.

2022-09-15 15:05 UTC, LKuemmel requested changes

2022-09-20 07:32 UTC, nalxnet commented on packages/modules/siemens_sentron/config.py
> +        self.configuration = configuration or SiemensSentronCounterConfiguration()
Ist angepasst.

2022-09-20 07:32 UTC, nalxnet commented on packages/modules/siemens_sentron/config.py
> +class SiemensSentronCounterSetup:
Ist angepasst.

2022-09-20 08:27 UTC, LKuemmel approved these changes

2022-09-20 08:30 UTC, merged