Smarthome...
snaptec/openWB pull request #2437
Opened 2022-10-08 12:33 UTC by okaegi

Neu wird nur noch Smartmq geladen. Der Parameter zum umschalten zwischen Smartmq und Smarthomehandler wurde entfernt. Die Hilfetexte für die Settings wurden leicht angepasst.

2022-10-09 18:43 UTC, yankee42 reviewed
Die Änderungen an den Hilfetexten habe ich mir nicht angesehen. Die scheinen mir mit dem Smarthome-Handler auch nichts zu tun zu haben?!

Wenn die `smarthomehandler.py` nicht mehr verwendet wird, sollte sie gelöscht werden.

2022-10-09 18:43 UTC, yankee42 commented on runs/services.sh
> +	openwbDebugLog "MAIN" 2 "Using smarthomemq"
Die Zeile könnte weg, denn sie fügt der Logausgabe in der Zeile davor nichts hinzu.

2022-10-09 18:43 UTC, yankee42 commented on runs/services.sh
> +	local smarthomehandler_disabled='smarthomehandler'
Das ganze Konstrukt mit den Variablen un der darauffolgenden Verzweigung habe ich gebraucht um nicht nur den Dienst zu starten und zu stoppen, sondern auch noch handzuhaben was passiert, wenn sich der konfigurierte Dienst geändert hat.

Wenn jetzt einer der Dienste wegfällt ist das alles hinfällig und das könnte vereinfacht werden auf das selbe Schema wie zum Beispiel direkt darüber die `mqttsub.py`.

2022-10-10 11:35 UTC, LKuemmel requested changes
Bitte die von @yankee42 angesprochenen Punkte nochmal überdenken.

2022-10-10 15:48 UTC, yankee42 commented on runs/services.sh
> +	  nohup python3 "$OPENWBBASEDIR/runs/smarthomemq.py" >> "$OPENWBBASEDIR/ramdisk/smarthome.log" 2>&1 &
Vom Code her sieht es jetzt für mich gut aus. Aber die Einrückung hat jetzt gemischt Tabs und Leerzeichen. Das sollte nicht sein. Es sollten immer Tabs sein.

2022-10-10 16:38 UTC, yankee42 commented
Die Änderungen am Code sehen für mich jetzt gut aus. Ich habe allerdings nur gelesen, nicht getestet.

Die Änderungen im HTML habe ich nicht reviewed.

2022-10-12 05:47 UTC, LKuemmel approved these changes

2022-10-12 05:48 UTC, merged