isss: support former modbus ids
snaptec/openWB pull request #2587
Opened 2023-01-13 10:14 UTC by LKuemmel

2023-01-16 14:54 UTC, benderl requested changes

2023-01-16 14:54 UTC, benderl commented on packages/modules/chargepoints/internal_openwb/chargepoint_module.py
> +            [meter_config(sdm.Sdm630, modbus_id=6), meter_config(sdm.Sdm630, modbus_id=106)]
Ich würde auch den B23 als LP2 der Duo unterstützen. Wer weiß, wann das mal benötigt wird.
```suggestion
            [meter_config(sdm.Sdm630, modbus_id=6),
             meter_config(sdm.Sdm630, modbus_id=106)
             meter_config(b23.B23, modbus_id=202)]
```

2023-01-17 08:20 UTC, LKuemmel commented on packages/modules/chargepoints/internal_openwb/chargepoint_module.py
> +             meter_config(b32.B32, modbus_id=201)],
ist geändert

2023-01-17 11:36 UTC, benderl approved these changes

2023-01-17 11:37 UTC, merged