fix switch between parent and NurLP
snaptec/openWB pull request #2677
Opened 2023-04-03 14:38 UTC by LKuemmel

2023-04-04 05:25 UTC, benderl requested changes

2023-04-04 05:25 UTC, benderl commented on runs/services.sh
> +			rm '/var/www/html/openWB/ramdisk/parentWB'
```suggestion
		if ((isss == 0)) && [ -f "$OPENWBBASEDIR/ramdisk/parentWB" ]; then
			rm "$OPENWBBASEDIR/ramdisk/parentWB"
```

2023-04-04 05:25 UTC, benderl commented on runs/services.sh
> +		if ((isss == 0)) && [ -f "/var/www/html/openWB/ramdisk/parentWB" ]; then
Ich würde den neuen If-Block vor Zeile 63 positionieren. Ansonsten ist nicht sichergestellt, dass er immer ausgeführt wird, wenn isss=0 ist.

2023-04-04 13:53 UTC, LKuemmel commented on runs/services.sh
> +		if ((isss == 0)) && [ -f "/var/www/html/openWB/ramdisk/parentWB" ]; then
umgesetzt

2023-04-05 04:55 UTC, benderl approved these changes

2023-04-05 08:11 UTC, merged