Add smart home module for AVM Home Automation (FRITZ!Box) switches
snaptec/openWB pull request #831
Opened 2020-12-31 13:05 UTC by fawick

This PR adds three scripts `on.py`, `off.py`, and `watt.py` that fulfill the same role as for other smarthome devices. The actors are addressed via a master device (usually a AVM FRITZ!Box router) which itself communications via DECT with the individual actors.

As the AVM Home Automation requires authentication to the DECT master and selection of the actor (here: via name), the call interface to smarthome scripts has been extended to take three additional call arguments. The subprocess call has been slightly refactored as the argument list is constructed explicitely prior to the call to `subprocess.Popen`.

2020-12-31 13:08 UTC, fawick commented on modules/smarthome/avmhomeautomation/avmcommon.py
> +    # fallback for storing password and credentials locally
NB: this is for my local development, as it allows me to run the scripts directly via command line instead of going through openWB

2021-01-01 23:47 UTC, benderl requested changes
Hello @fawick and thank you forthis module.
I have a suggestion to change `on.py`, `off.py`and `watt.py` to a common codebase in `avmcommon.py`. The three files share about 98% of their code, so this should be a own function in the common file. `on.py`and `off.py` can shrink down to something like `connect()` and `switchDevice( on/off )`. Same for `watt.py`: `connect()` and then `getActualPower()`.

This will reduce the duplicate code and maintainance will be much easier.

2021-01-01 23:47 UTC, benderl commented on modules/smarthome/avmhomeautomation/off.py
> +time_string = time.strftime("%m/%d/%Y, %H:%M:%S avmhomeautomation on.py", named_tuple)
Typo: should be `... off.py`

2021-01-01 23:47 UTC, benderl commented on modules/smarthome/avmhomeautomation/off.py
> +devicenumber=str(sys.argv[1])
Please always surround equal signs with spaces. There are some more lines without them.

2021-01-02 00:02 UTC, fawick commented
> change on.py, off.pyand watt.py to a common codebase in avmcommon.py

Will do, most gladly! I had been replicating the style and naming scheme which I found in the existing smarthome modules to maximize recognizability for the other authors. There sure is a lot of repeated code in those.

2021-01-02 00:19 UTC, benderl commented
You are right, the other modules should also use a common file for shared code.
@okaegi can you do this?

2021-01-02 02:09 UTC, fawick commented on modules/smarthome/avmhomeautomation/off.py
> +time_string = time.strftime("%m/%d/%Y, %H:%M:%S avmhomeautomation on.py", named_tuple)
Done

2021-01-02 02:09 UTC, fawick commented on modules/smarthome/avmhomeautomation/off.py
> +devicenumber=str(sys.argv[1])
Done

2021-01-02 08:27 UTC, okaegi commented
@benderl i will have a look during next week. At least the logging could be moved for each device. Can you push everything to nightly ?
@fawick do you were able to do a none impact test for shelly for example or should i do one ?
Regards Oliver

2021-01-02 08:50 UTC, fawick commented
@okaegi As I do not have access to Shelly devices (don't own one, know nobody who does) I'd be glad if you could help out. Am I correct to assume that the test is primarily about whether the three additional command line parameters have an effect on the other scripts in `modules/smarthome`?

2021-01-02 09:01 UTC, okaegi commented
> Am I correct to assume that the test is primarily about whether the three additional command line parameters have an effect on the other scripts in `modules/smarthome`?

Yes excatly, that none of the existing devices are harmed by the change..
I have shelly and stiebel and i will test them.

2021-01-02 09:45 UTC, fawick commented
Thanks for clarifying! 

For what its worth, before I submitted the PR I did a grep against `sys.argv` in all smarthome modules and could not find any accesses to anything beyond `sys.argv[3]` for all prior modules except `http/*` which uses `sys.argv[4]` for the URL parameter. Where command line parameters are accessed, they are indexed explicitely. While `getopt` is imported at many places, no API of the `getopt` package is used.  I dare to say that the existence of additional command line parameters should not cause any trouble.

However, there exists a non-zero chance that I introduced a regression bug in the ordering of arguments in `runs/smarthomehandler.py`. So any additional testing  is helpful. I am grateful to you for offering to do these tests. Thank you!

2021-01-02 11:44 UTC, benderl approved these changes
Looks perfect! Thank you.

2021-01-03 14:24 UTC, merged