SoC Peugeot: kombiniere manuell+berechnung und PSA modul, ersetzt #899
snaptec/openWB pull request #911
Opened 2021-01-16 23:29 UTC by MartinRinas

Ersetzt PR899

PSA liefert während des Ladens derzeit keine SoC Aktualisierung. In der Modulkonfiguration für Peugeot kann nun zusätzlich Manuell+Berechnung aktiviert werden.
Dies sorgt dafür dass der initiale SoC zu Ladebeginn über die API abgerufen wird, während des Ladevorgangs wird der SoC dann basierend auf dem Ladezähler berechnet.

2021-01-19 17:56 UTC, MartinRinas reviewed
updated UI to hide pack size and efficiency while manual and calc is not selected.

2021-01-20 07:32 UTC, benderl requested changes
Danke für den PR!
Wir haben in den vergangenen Wochen viel Zeit investiert, um die SoC-Module generisch für alle LP nutzen zu können. Bitte passe Deinen Code so an, dass nicht nur LP1 sondern auch LP2 mit diesem Modul einwandfrei funktioniert. In der `main.sh` habe ich die entsprechenden Stellen kommentiert. Die Änderungen in der `modulconfiglp.php` übernimmst Du bitte auch für LP2.

2021-01-20 07:32 UTC, benderl commented on modules/soc_mypeugeot/main.sh
> +if (($mypeugeot_soccalclp1 == 0)); then #manual calculation not enabled, using existing logic
Bitte je nach Ladepunkt prüfen! Mit dieser Logik wird auch an LP2 die Einstellung von LP1 verwendet.
Dazu in der Case-Abfrage zu Beginn eine neue Variable `$soccalc` definieren und je nach Ladepunkt mit `$mypeugeot_soccalclp1` oder `$mypeugeot_soccalclp2` initialisieren.

2021-01-20 07:32 UTC, benderl commented on modules/soc_mypeugeot/main.sh
> +	chargestat=$(</var/www/html/openWB/ramdisk/chargestat)
`chargestat`ist ebenfalls nur für LP1 gültig. LP2 verwendet `chargestats1`. Vorgehensweise analog zu den anderen Dateinamen in der Case-Anweisung.

2021-01-20 07:32 UTC, benderl commented on modules/soc_mypeugeot/main.sh
> +fi
Am Ende der Datei fehlt ein Zeilenumbruch.

2021-01-20 07:32 UTC, benderl commented on web/settings/modulconfiglp.php
> +													<input type="radio" name="mypeugeot_soccalclp1" id="mypeugeot_soccalclp1Off" value="0"<?php if($mypeugeot_soccalclp1old == 0) echo " checked=\"checked\"" ?>>Nein
Die neue Einstellung `mypeugeot_soccalclp1` (und auch für `...lp2`) müssen in der `openwb.conf` eingetragen werden. Solche Änderungen werden durch die `runs/atreboot.sh` durchgeführt, die nach einem Update und beim Neustart ausgeführt wird. Bitte dort analog zu den vorherigen Zeilen in der `atreboot.sh` einfügen: https://github.com/snaptec/openWB/blob/dfd9a5d17f3e4856f20df73ec99172e72c7776e0/runs/atreboot.sh#L2810

2021-01-20 08:31 UTC, MartinRinas commented
Vielen Dank, das kann ich gern noch ändern und anpassen - kommt im Laufe des Abends.

2021-01-20 19:58 UTC, MartinRinas commented
@benderl alles erledigt und funktionert bei mir auch soweit. Hoffe dass ich nichts übersehen habe, wenn doch werde ich es bestimmt bald erfahren ;)

2021-01-21 10:08 UTC, benderl approved these changes
Sieht gut aus!

2021-01-21 10:08 UTC, merged