MyOpel SoC Module: add man+calc option
snaptec/openWB pull request #937
Opened 2021-01-23 17:50 UTC by MartinRinas

* MyOpel SoC Module: add man+calc option
* added soCLog function to have some detail in the log, currently its either debug or nothing

2021-01-23 18:03 UTC, MartinRinas commented
Diese Änderungen müssen noch in die updateconfig:

`if ! grep -Fq "myopel_soccalclp1=" /var/www/html/openWB/openwb.conf
then
	echo "myopel_soccalclp1=0" >> /var/www/html/openWB/openwb.conf
fi
if ! grep -Fq "myopel_soccalclp2=" /var/www/html/openWB/openwb.conf
then
	echo "myopel_soccalclp2=0" >> /var/www/html/openWB/openwb.conf`

2021-01-25 15:23 UTC, benderl commented on runs/atreboot.sh
> +<<<<<<< HEAD
Hier ist wohl bei einem Rebase oder Pull etwas übrig geblieben.

2021-01-25 15:26 UTC, benderl requested changes
Kannst Du bitte die Änderungen an der atreboot.sh entfernen?

2021-01-25 17:13 UTC, MartinRinas commented
done.

2021-01-25 17:58 UTC, benderl approved these changes
Sieht gut aus.

2021-01-25 17:58 UTC, merged